<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>_09_DIsection</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServicesLayer\ServicesLayer.csproj" />
  </ItemGroup>

</Project>
